---
# Source: argocd-applicationset/templates/projects.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: herewith-staging
  namespace: argo-cd
status: {}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - '*'
  sourceRepos:
    - '*'
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: herewith-dev
  namespace: argo-cd
status: {}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - '*'
  sourceRepos:
    - '*'
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: herwith-qa
  namespace: argo-cd
status: {}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - '*'
  sourceRepos:
    - '*'
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: herewith-pre-prod
  namespace: argo-cd
status: {}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - '*'
  sourceRepos:
    - '*'
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: herewith-production
  namespace: argo-cd
status: {}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - '*'
  sourceRepos:
    - '*'
---
# Source: argocd-applicationset/templates/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: herewith-argo-staging-appset
  namespace: argo-cd
spec:
  generators:
    - git:
        repoURL: https://github.com/tjdetwill007/helm-values.git
        revision: master
        directories:
        - path: argocd-applicationset-values/herewith-staging/*
  template:
    metadata:
      name: '{{.path.basename}}'
      namespace: herewith-staging-ns
    spec:
      project: herewith-staging
      sources:
        - repoURL: git@github.com:/quoori/helm-charts
          targetRevision: v1.0.4
          path: charts/superchart
          helm:
            valueFiles:
            - $values/values.yaml
        - repoURL: https://github.com/tjdetwill007/helm-values.git
          targetRevision: master
          path: '{{.path.path}}'
          ref: values
      destination:
        server: https://6B2FDC16BD92F6ADEECB36735FC75CAE.gr7.eu-central-1.eks.amazonaws.com
        namespace: backend
---
# Source: argocd-applicationset/templates/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: herewith-argo-dev-appset
  namespace: argo-cd
spec:
  generators:
    - git:
        repoURL: https://github.com/tjdetwill007/helm-values.git
        revision: master
        directories:
        - path: argocd-applicationset-values/herewith-dev/*
  template:
    metadata:
      name: '{{.path.basename}}'
      namespace: herewith-dev-ns
    spec:
      project: herewith-dev
      sources:
        - repoURL: git@github.com:/quoori/helm-charts
          targetRevision: v1.0.4
          path: charts/superchart
          helm:
            valueFiles:
            - $values/values.yaml
        - repoURL: https://github.com/tjdetwill007/helm-values.git
          targetRevision: master
          path: '{{.path.path}}'
          ref: values
      destination:
        server: https://6B2FDC16BD92F6ADEECB36735FC75CAE.gr7.eu-central-1.eks.amazonaws.com
        namespace: dev-backend
---
# Source: argocd-applicationset/templates/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: herewith-argo-qa-appset
  namespace: argo-cd
spec:
  generators:
    - git:
        repoURL: https://github.com/tjdetwill007/helm-values.git
        revision: master
        directories:
        - path: argocd-applicationset-values/herwith-qa/*
  template:
    metadata:
      name: '{{.path.basename}}'
      namespace: herewith-qa-ns
    spec:
      project: herwith-qa
      sources:
        - repoURL: git@github.com:/quoori/helm-charts
          targetRevision: v1.0.4
          path: charts/superchart
          helm:
            valueFiles:
            - $values/values.yaml
        - repoURL: https://github.com/tjdetwill007/helm-values.git
          targetRevision: master
          path: '{{.path.path}}'
          ref: values
      destination:
        server: https://6B2FDC16BD92F6ADEECB36735FC75CAE.gr7.eu-central-1.eks.amazonaws.com
        namespace: qa-backend
---
# Source: argocd-applicationset/templates/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: herewith-argo-pre-prod-appset
  namespace: argo-cd
spec:
  generators:
    - git:
        repoURL: https://github.com/tjdetwill007/helm-values.git
        revision: master
        directories:
        - path: argocd-applicationset-values/herewith-pre-prod/*
  template:
    metadata:
      name: '{{.path.basename}}'
      namespace: herewith-pre-prod-ns
    spec:
      project: herewith-pre-prod
      sources:
        - repoURL: git@github.com:/quoori/helm-charts
          targetRevision: v1.0.4
          path: charts/superchart
          helm:
            valueFiles:
            - $values/values.yaml
        - repoURL: https://github.com/tjdetwill007/helm-values.git
          targetRevision: master
          path: '{{.path.path}}'
          ref: values
      destination:
        server: https://6B2FDC16BD92F6ADEECB36735FC75CAE.gr7.eu-central-1.eks.amazonaws.com
        namespace: pre-prod-backend
---
# Source: argocd-applicationset/templates/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: herewith-argo-production-appset
  namespace: argo-cd
spec:
  generators:
    - git:
        repoURL: https://github.com/tjdetwill007/helm-values.git
        revision: master
        directories:
        - path: argocd-applicationset-values/herewith-production/*
  template:
    metadata:
      name: '{{.path.basename}}'
      namespace: herewith-production-ns
    spec:
      project: herewith-production
      sources:
        - repoURL: git@github.com:/quoori/helm-charts
          targetRevision: v1.0.4
          path: charts/superchart
          helm:
            valueFiles:
            - $values/values.yaml
        - repoURL: https://github.com/tjdetwill007/helm-values.git
          targetRevision: master
          path: '{{.path.path}}'
          ref: values
      destination:
        server: https://6B2FDC16BD92F6ADEECB36735FC75CAE.gr7.eu-central-1.eks.amazonaws.com
        namespace: prod-backend
